INSERT INTO songs (url,difficulty,genre, song_title, song_origin , player_targets)
VALUES ('HTUq3Ik1GHM','easy','videogame','Sanctuary','Kingdom Hearts 2',NULL),
('IOeCpYhwbfY','easy','anime','Kimi Jana Dame Mitai','Nozaki-Kun',NULL),
('1oOBjyOKu2o','easy','anime','Crossing Fields','Sword Art Online',NULL),
('A9zlXUSuUeo','easy','videogame','Reach Out To The Truth','Persona 4',NULL),
('Ior8kfPldEw','easy','videogame','Kamura Village','Monster Hunter Rise',NULL),
('tSwBFZ6AnQY','easy','videogame','Invincible Rainbow Arrow','AI: The Somnium Files',NULL),
('vdcddjV0l5o','easy','anime','Tomorrow','Konosuba',NULL),
('NZcWaSAIrmI','easy','anime','Pegasus Fantasy','Saint Seiya',NULL),
('SMmWckDugkQ','easy','videogame','Disaster of Passion','Guilty Gear Strive',NULL),
('xi0M9SIaLb4','easy','videogame','Engage the Enemy','Xenoblade',NULL),
('twPSaCABakA','easy','videogame','Green Greens','Kirbys Dream Land',NULL),
('dAAnOQxL5HI','easy','videogame','13th Struggle','Kingdom Hearts 2',NULL),
('0jXTBAGv9ZQ','easy','videogame','Halo Theme','Halo',NULL),
('AjAxsWgEexI','easy','videogame','Storm Alert Theem 06','Weather Channel',NULL),
('W6q1AWnjNiU','tough','anime','Tabi no Tochuu','Spice and Wolf',NULL),
('BSsfjHCFosw','tough','videogame','E1M1/At Dooms Gate','Doom',NULL),
('Ln6NpxYb73k','tough','anime','Saturday Night Question','MMO Junkie',NULL),
('GVhAkQuZvLQ','tough','videogame','Athletic Theme','Mario World',NULL),
('SJwh3erQlyE','tough','videogame','Title Theme','Pictionary(NES)',NULL),
('KE2ncZsxz50','tough','anime','03 GAMERS! TV','GAMERS!',NULL),
('yCI0l-BRxj8','tough','videogame','Opening Stage Theme','Megaman X2',NULL),
('fTvjc12new0','tough','videogame','Tornado Man Theme','Megaman 9',NULL),
('5W_bFLwB0WY','tough','videogame','Overworld Theme','The Legend of Zelda: Spirit Tracks',NULL),
('gMof02uM5Qc','tough','videogame','Ebb and Flow','Splatoon 2',NULL),
('QOjG6QefMeE','tough','anime','???','Kakegururi',NULL),
('LXukwNQG0uA','tough','videogame','Marble Zone Theme','Sonic 1',NULL),
('4pzxfgzhOvE','tough','videogame','Zanarkand','Final Fantasy X',NULL),
('du3Zz4HrGXA','tough','videogame','Gusty Garden Theme','Mario Galaxy',NULL),
('2-_unC-g_rY','impossible','videogame','This is true Love Makin','Capcom vs. SNK 2',NULL),
('f96NHr_KpMU','impossible','videogame','Gate K9','Cyberpunk 2077',NULL),
('vAX6rPn8f1U','impossible','videogame','Pain','Cyberpunk 2077',NULL),
('cyWTgLf-piE','impossible','videogame','Dracula Castle','Castlevania SOTN',NULL),
('RO0s2oudSog','impossible','videogame','Paradise (Stay Forever)','Paradise Killer',NULL),
('K2GnhcYdcIk','impossible','videogame','Nine Ball Theme','Armored Core',NULL),
('skKHJptFYSk','impossible','videogame','The Vampire Saga','Guilty Gear Korean OST',NULL),
('yyDMMFxImrA','impossible','videogame','Lobby','Library of Ruina',NULL),
('l-Tsa6Ji8eM','impossible','anime','Gamay Obera','Pop Team Epic',NULL),
('pEfblikvZsQ','impossible','videogame','Midori Eyes','Paradise Killer',NULL),
('TA0yE1hlMRE','impossible','videogame','Noize','River City Girls',NULL),
('TMYfULr80jg','impossible','videogame','Nachtflugel','Kingdom Hearts 3',NULL),
('etFD_tfgzM4','impossible','videogame','Pure','Kimi ni no Todoke',NULL),
('MgMXWnWH1TA','special','videogame','Cutting Edge of Notion','Star Ocean 3','Player1'),
('nOj_A3aZxGs','special','videogame','String Theocracy','Library of Ruina','Player1'),
('_uZO4U9N86s','special','videogame','Roar of Steel','Trails to Azure','Player1'),
('X_-2qMyfj5A','special','videogame','OverTrip (Cammy Theme)','Street Fighter 6','Player1'),
('qAGvQDoL5s4','special','anime','Afternoon of Konoha','Naruto','Player1'),
('Um5EbReY7rA','special','videogame','Sophisticated Fight','Tails in the Sky','Player1'),
('R3YcANVqmIM','special','videogame','Battle 1','SMT: Strange Journey','Player2'),
('B7gGacb8cO4','special','videogame','Its pizza time!','Pizza Tower','Player2'),
('0EUaVEA8Fcg','special','videogame','Voyage of Promise','Bloodstained: ROTN','Player2'),
('KQAb4mbyAnw','special','videogame','High Seas Hi-Jinx','Cuphead','Player2'),
('BPOSBDrqoDY','special','videogame','Stab the Sword of Justice','Star Ocean 2 (PSX)','Player2'),
('mdqNshgDwtQ','special','videogame','Silent Hill Theme','Silent Hill','Player3'),
('4HEhU5gAXbc','special','videogame','Battle 2','Octopath Traveler','Player3'),
('ysPtBjY8o_A','special','videogame','Coalescence','Risk of Rain','Player3'),
('LDnENTDuAiI','special','videogame','Silver for Monsters','Witcher 3','Player3'),
('5kJkAoaW634','special','videogame','Sixteen Strikes','Baldurs Gate 3','Player3'),
('Y9bQSukPrCM','easy','videogame','Bright Sandstorm','Fire Emblem Engage',NULL);
